apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # labels of deployemnt resource
  labels:
    app: app1
spec:
  replicas: 2
  selector:
  # As we have many pods ,we should give what labels the deployment to match
    matchLabels:
      app: app1
  # pod template
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: jayakrishna1993/app1:1.0.0
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: app1-service
spec:
  selector:     #labels are used as selectors
    app: app1
  ports:
  - protocol: TCP
    port: 80    #service port
    targetPort: 80   #target container port
